const CAR_NAME_LENGTH_MAX = 5;
const CAR_NAME_LENGTH_MIN = 1;

const CAR_NAME_LENGTH = Object.freeze({
  min: CAR_NAME_LENGTH_MIN,
  max: CAR_NAME_LENGTH_MAX,
});

const RANDOM_NUMBER_MIN = 0;
const RANDOM_NUMBER_MAX = 9;

const RANDOM_NUMBER = Object.freeze({
  min: RANDOM_NUMBER_MIN,
  max: RANDOM_NUMBER_MAX,
});

const MIN_FORWARD_CONDITION = 4;

export { CAR_NAME_LENGTH, RANDOM_NUMBER, MIN_FORWARD_CONDITION };
